stages:
- name: Install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install -g npm-cli-login && npm-cli-login --quotes && npm install
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_EMAIL: devops@demandcluster.com
      NPM_REGISTRY: https://registry.npmjs.org
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_EMAIL
      targetKey: NPM_EMAIL
    - sourceName: cicd
      sourceKey: NPMJS_USER
      targetKey: NPM_USERNAME
    - sourceName: cicd
      sourceKey: NPMJS_PASS
      targetKey: NPM_PASS
- name: Lint
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run lint
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run test
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
- name: Release
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: chown 1000:1000 /home/jenkins -R && npx semantic-release
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_REGISTRY: https://registry.npmjs.org
    envFrom:
    - sourceName: cicd
      sourceKey: NPMJS_USER
      targetKey: NPM_USERNAME
    - sourceName: cicd
      sourceKey: DEVOPS_TOKEN
      targetKey: GH_TOKEN
    - sourceName: cicd
      sourceKey: NPMJS_PASS
      targetKey: NPM_PASSWORD
timeout: 60
notification: {}
