stages:
- name: Install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install 
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_EMAIL: devops@demandcluster.com
      NPM_REGISTRY: https://npm.demandcluster.com
      NPM_USER: demandcluster
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_PASS
      targetKey: NPM_PASS
- name: Lint
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run lint
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run test
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
- name: Release
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: chown 1000:1000 /home/jenkins -R && npx semantic-release --no-ci
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_EMAIL: rondlite@gmail.com
      NPM_USERNAME: rondlite
    envFrom:
    - sourceName: cicd
      sourceKey: DEVOPS_TOKEN
      targetKey: GH_TOKEN
    - sourceName: cicd
      sourceKey: NPMJS_TOKEN
      targetKey: NPM_TOKEN
timeout: 60
notification: {}
